# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  database: techstorm_test

production:
  <<: *default
  database: techstorm_production
  username: techstorm
  password: <%= ENV['TECHSTORM_DATABASE_PASSWORD'] %>
